### ISSUE TITLE
Help with DVP vs DVPHoldable

### ISSUE THREAD

**Issue by onigiri-x** [ConsenSys/UniversalToken#103]
Hi there,
Victor here, looking for some advise on the DVP contracts.

Basically in the project we are looking to use ERC20Holdable and do swaps for ERC1400

I think I can achieve this using DVP.sol normal

But I noticed the DVPHoldable contract, and was left a little confused. What is the difference between them? Are they used together? If I create a request trade in the DVP contract, are the tokens on escrow/hold ? Or do I need to use both the DVP to setup the trade and the DVPHoldableLockable to lock up the tokens until it is executed? Tokens are only ever transferred on execute it seems.

Thanks!

**Comment by gauthierpetetin** [comment]
Hello @victorwiebe ,
If you have a look at this [DVP overview image](https://github.com/ConsenSys/UniversalToken/blob/master/images/Picture17.png):
- [DVP.sol](https://github.com/ConsenSys/UniversalToken/blob/master/contracts/tools/DVP.sol) allows to perform both "DVP with allowances" and "DVP with escrows"
- [DVPHoldableLockable.sol](https://github.com/ConsenSys/UniversalToken/blob/master/contracts/tools/DVPHoldableLockable.sol) allows to perform both "DVP with holds"
If the token you use is "holdable", which seems to be the case since you're using ERC20Holdable, I recommend using DVPHoldableLockable as it offers both "certainty of execution" and "reliability of investor registry".
