### ISSUE TITLE
Deploy the ERC1820 on a private network

### ISSUE THREAD

**Issue by soragXYZ** [ConsenSys/UniversalToken#128]
Hi!

I'm trying to deploy all the contracts from your repo on a private network (IBFT2), where the gas price is set to 0, but I'm unable to deploy the ERC1820

Since there is no gas fee in my network, I changed the rawTx to fit my needs, but when I deploy the contract with truffle, the contract address returned is Null

Do you have any idea how I can solve this issue ?

Thanks

**Comment by soragXYZ** [comment]
Ok

**Comment by gauthierpetetin** [comment]
Hi @soragXYZ ,
The ERC1820 deployment transaction shall not be modified otherwise, its address won't be "0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24" anymore.
As "0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24" is [hardcoded](https://github.com/ConsenSys/UniversalToken/blob/master/contracts/tools/ERC1820Client.sol), it shall not be different.
The only way we've managed to deploy ERC1820 on private networks with gas price set to 0, is to include erc1820 directly in the genesis block.
